repos:
  - repo: local
    hooks:
      - id: lint
        name: eslint
        entry: pnpm --silent lint
        language: system
        types_or: [ts, tsx, javascript]
        pass_filenames: false
      - id: css-lint
        name: stylelint
        entry: pnpm --silent css-lint
        language: system
        types: [css]
        pass_filenames: false
      - id: typecheck
        name: astro check
        entry: pnpm --silent typecheck
        language: system
        types_or: [ts, tsx, astro]
        pass_filenames: false
